name = "HDF5Logger"
uuid = "a770b2f2-aca6-5e76-943a-580dc53aa03d"
version = "1.0.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
